public class Car {
// class starts here

public String carColor = '' ;
Public String carName ='';
// if we do not write access modifier, by default its private.

integer maxspeedKmPerHr =150;
public void switchOn(){
// Method Body
system.debug('starting the car');
}
Public void drive(){
system.debug('driving'+ carName);
}
public void driveAtMaxSpeed(){
String drivingDescription = ('driving'+ carName);
}
public void driveAtMaxSpeed(){
String drivingDescription ='driving'+ carName + 'at' +maxSpeedKmPerHr + 'km/h';
system.debug(drivingDescription);

}


}
